# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18QDkmA1EL88ic4jAO51ZZJMl_MlKJGyD

Write a program that asks user to enter a Color/Fruit/Animal name and it should tell which category belongs to , like its is a fruit or color or Animal
"""

Colors=["yellow","green","white","black"]
Fruits=["apple","papaya","mango","orange"]
Animals=["tiger","lion","deer","zebra"]
value=input("enter a color , fruit or animal")
if value in Colors:
    print("it is a color")
if value in Fruits:
    print("it is a fruit")
if value in Animals:
    print("it is an animal")

""" Write a program that asks user to enter two items and it tells you if they both are in same category or not. For example if I enter yellow and Black, it will print "Both are colors" but if I enter yellow and Tiger it should print "They don't belong to same category""""

Colors=["yellow","green","white","black"]
Fruits=["apple","papaya","mango","orange"]
Animals=["tiger","lion","deer","zebra"]
value=input("enter a value")
value1=input("enter a value ")
if value in Colors and  value1 in Colors:
  print("both belong to colors")
elif value in Fruits  and value1 in Fruits:
  print("both belong to colors")
elif value in Animals and value1 in Animals:
  print("both belong to animals")
else:
  print("both belong different categories")

"""Write a python program that can tell you if your grade score good or not . Normal Score range is 40 to 60.

  i. Ask user to enter his score.

  ii. If it is below 40 to 60 range then print that score is low

  iii. If it is above 60 then print that it is good otherwise print that it is normal
"""

score=int(input("enter your score"))
if score < 40:
  print("score is low ")
if score > 40 and score < 60:
  print("score is normal")
if score>60:
  print("score is good")

"""After appearing in exam 10 times you got this result,

result = ["Pass","Fail","Fail","Pass","Fail","Pass","Pass","Fail","Fail","Fail"]

Using for loop figure out how many times you got Pass
"""

result= ["Pass","Fail","Fail","Pass","Fail","Pass","Pass","Fail","Fail","Fail"]
count=0

for i in result:
  if i=="Pass":
     count+=1
print("number of times the student has passed is ",count)
count1=len(result)-count
print("number of times the student has failed is " , count1)

for i in range(1,5):
  for j in range(i):
    print("*",end="")
  print()
for i in range(5,0,-1):
  for j in range(i):
    print("*",end="")
  print()

"""Lets say you are running a 50 km race. Write a program that,

Upon completing each 10 km asks you "are you tired?"
If you reply "yes" then it should break and print "you didn't finish the race"
 If you reply "no" then it should continue and ask "are you tired" on every km
If you finish all 50 km then it should print congratulations message
"""

for i in range(1,51):
  if i%10==0:
    n=input("are you tired ")
    if n=="yes":
      print("you did not finish the race")
      break
if i==50:
  print("congratulations")
else:
  print("well tried , you ran " + str(i)+ "km")

"""Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included)."""

for i in range(1500,2701):
  if i%7==0 and i%5==0:
    print(i)

"""Print square of all numbers between 10 to 20 except even numbers"""

for i in range(11,20):
  if i%2!=0:
    print(i*i)

"""Your Marks for five Test(test1 to test5) looks like this,

marks_list = [65, 75, 2100, 95, 83]

Write a program that asks you to enter marks and program should tell you in which test that marks occurred. If marks is not found then it should print that as well.
"""

test_list=["test1","test2","test3","test4","test5"]
marks_list = [65, 75, 2100, 95, 83]
ip=int(input("enter the marks"))
test=-1
for i in range(len(marks_list)):
  if ip==marks_list[i]:
    test=i
    break
if test!=-1:
  print("you got "+str(ip)+ " in " +test_list[test])
else:
  print("you entered wrong marks")